/**
 * Offline support.
 *
 * The shell is precached so the portal opens with no network at all - which is
 * the point of a local-first tool. Everything else is served stale-while-
 * revalidate, and navigations fall back to the cached index so a deep link
 * still resolves offline.
 *
 * The block below is generated by `npm run build:sw`; edit that script, not this.
 */

/* --- precache:start --- */
const CACHE_VERSION = '2e6bd0c1a8';
const PRECACHE = [
  './',
  './assets/icon-maskable.svg',
  './assets/icon.svg',
  './index.html',
  './manifest.webmanifest',
  './src/core/diff.js',
  './src/core/i18n.js',
  './src/core/invite.js',
  './src/core/modifiers.js',
  './src/core/registry.js',
  './src/core/search.js',
  './src/core/store.js',
  './src/core/targets.js',
  './src/core/techniques.js',
  './src/core/template.js',
  './src/core/tokens.js',
  './src/core/utils.js',
  './src/data/categories.js',
  './src/data/contact.js',
  './src/data/engines/business.js',
  './src/data/engines/code.js',
  './src/data/engines/communication.js',
  './src/data/engines/content.js',
  './src/data/engines/data.js',
  './src/data/engines/debug.js',
  './src/data/engines/index.js',
  './src/data/engines/learning.js',
  './src/data/engines/productivity.js',
  './src/data/engines/research.js',
  './src/data/engines/strategy.js',
  './src/main.js',
  './src/ui/app.js',
  './src/ui/components.js',
  './src/ui/dom.js',
  './src/ui/footer.js',
  './src/ui/icons.js',
  './src/ui/modal.js',
  './src/ui/palette.js',
  './src/ui/router.js',
  './src/ui/shortcuts.js',
  './src/ui/toast.js',
  './src/ui/views/builder.js',
  './src/ui/views/category.js',
  './src/ui/views/generator.js',
  './src/ui/views/home.js',
  './src/ui/views/search.js',
  './src/ui/views/settings.js',
  './src/ui/views/stats.js',
  './src/ui/views/vault.js',
  './styles.css',
];
/* --- precache:end --- */

const CACHE_NAME = `strategic-portal-${CACHE_VERSION}`;

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE_NAME)
      // A single failing asset must not abort the whole install, so each one is
      // added on its own and misses are tolerated.
      .then((cache) => Promise.allSettled(PRECACHE.map((asset) => cache.add(asset))))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) => Promise.all(names.filter((name) => name !== CACHE_NAME).map((name) => caches.delete(name))))
      .then(() => self.clients.claim()),
  );
});

/**
 * The cached shell to answer a navigation with when the network is gone.
 *
 * A navigation may not be answered with a response whose `redirected` flag is
 * set - the browser rejects it outright, so the page fails to load rather than
 * falling back. Static hosts routinely redirect `/index.html` to `/`, and this
 * one does: precaching `./index.html` there stores exactly such a response, so
 * the old fallback turned "offline" into a blank error page until some later
 * online visit happened to overwrite the entry. `./` is fetched directly and
 * carries no redirect, so it is preferred, and anything redirected is refused.
 */
async function offlineShell() {
  for (const key of ['./', './index.html']) {
    const cached = await caches.match(key);
    if (cached && !cached.redirected) return cached;
  }
  return Response.error();
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put('./', copy));
          return response;
        })
        .catch(() => offlineShell()),
    );
    return;
  }

  event.respondWith(
    caches.match(request).then((cached) => {
      const network = fetch(request)
        .then((response) => {
          if (response.ok) {
            const copy = response.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
          }
          return response;
        })
        .catch(() => cached);
      return cached ?? network;
    }),
  );
});

self.addEventListener('message', (event) => {
  if (event.data === 'skip-waiting') self.skipWaiting();
});
